MONGODB_HOST: mongodb-{{ env }}.pavandevops.fun
REDIS_HOST: redis-{{ env }}.pavandevops.fun
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.pavandevops.fun
CART_HOST: cart.backend-alb-{{ env }}.pavandevops.fun
USER_HOST: user.backend-alb-{{ env }}.pavandevops.fun
RABBITMQ_HOST: rabbitmq-{{ env }}.pavandevops.fun
MYSQL_HOST: mysql-{{ env }}.pavandevops.fun
SHIPPING_HOST: shipping.backend-alb-{{ env }}.pavandevops.fun
PAYMENT_HOST: payment.backend-alb-{{ env }}.pavandevops.fun
