MONGODB_HOST: mongodb-{{ env }}.pavandevops.fun
REDIS_HOST: redis-{{ env }}.pavandevops.fun
CATALOGUE_HOST: catalogue-{{ env }}.pavandevops.fun
CART_HOST: cart-{{ env }}.pavandevops.fun
USER_HOST: user-{{ env }}.pavandevops.fun
RABBITMQ_HOST: rabbitmq-{{ env }}.pavandevops.fun
MYSQL_HOST: mysql-{{ env }}.pavandevops.fun
SHIPPING_HOST: shipping-{{ env }}.pavandevops.fun
PAYMENT_HOST: payment-{{ env }}.pavandevops.fun
