MONGODB_HOST: mongodb.pavandevops.fun
REDIS_HOST: redis.pavandevops.fun
CATALOGUE_HOST: catalogue.pavandevops.fun
CART_HOST: cart.pavandevops.fun
USER_HOST: user.pavandevops.fun
RABBITMQ_HOST: rabbitmq.pavandevops.fun
MYSQL_HOST: mysql.pavandevops.fun
SHIPPING_HOST: shipping.pavandevops.fun
PAYMENT_HOST: payment.pavandevops.fun
